### ISSUE TITLE
JSON String contains space

### ISSUE THREAD

**Issue by wuriyanto48** [Bhinneka/kece#1]
`{\"id\": 1,\"name\": \"wuriyanto\"}`
cannot store json string contains space like above json data.

**Comment by wuriyanto48** [comment]
i think possible to remove all spaces before store operation

**Comment by agungdwiprasetyo** [comment]
Example: `{\"id\": 1,\"name\": \"agung dwi prasetyo\"}`
Don't remove all space, it will changes to the stored data.
